spring:
  datasource:
    url: jdbc:h2:mem:main-server-db
    driverClassName: org.h2.Driver
    username: user
    password: 12345
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
stats-server:
  uri: http://localhost:9090
