spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6666/main-server
    username: user
    password: 12345
logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO
          jpa.JpaTransactionManager: DEBUG
        transaction: INFO
        transaction.interceptor: TRACE
stats-server:
  uri: http://stats-server:9090
hibernate:
  show_sql: true
  jdbc:
    time_zone: UTC
