spring:
  application:
    name:
      collector

logging:
  level:
    ru.yandex.practicum.telemetry.collector: TRACE
    ru.yandex.practicum.kafka: TRACE
    org:
      springframework: INFO
      apache.kafka: WARN

collector:
  kafka:
    producer:
      properties:
        bootstrap.servers: localhost:9092
        client.id: "stats.collector"
        key.serializer: org.apache.kafka.common.serialization.LongSerializer
        value.serializer: ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
      topics:
        user-actions: stats.user-actions.v1

grpc:
  server:
    port: 59091
