spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6688/category-server
    username: user
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 0

hibernate:
  show_sql: true
  jdbc:
    time_zone: UTC

main-service:
  uri: http://main-service
