spring:
  application:
    name: aggregator

logging:
  level:
    ru.yandex.practicum.telemetry.aggregator: TRACE
    ru.yandex.practicum.kafka: TRACE
    org:
      springframework: INFO
      apache.kafka: WARN

aggregator:
  kafka:
    producerConfig:
      properties:
        bootstrap.servers: localhost:9092
        client.id: "stats.aggregator"
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
      topics:
        events-similarity: stats.events-similarity.v1
    consumerConfig:
      properties:
        bootstrap.servers: localhost:9092
        group.id: "aggregator-consumer-group"
        key.deserializer: org.apache.kafka.common.serialization.LongDeserializer
        value.deserializer: ru.yandex.practicum.kafka.deserializer.UserActionDeserializer
        max.poll.records: 500
        fetch.min.bytes: 1
        fetch.max.wait.ms: 500
        enable.auto.commit: true
      topics:
        user-actions: stats.user-actions.v1
