spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6677/user-server
    username: user
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          event-service:
            connectTimeout: 5000
            readTimeout: 5000

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 50
        failureRateThreshold: 50
        waitDurationInOpenState: 60000
        minimumNumberOfCalls: 10

server:
  port: 0

hibernate:
  show_sql: true

stats-server:
  uri: http://stats-server:9090

category-service:
  uri: http://category-service

user-service:
  uri: http://user-service

event-service:
  uri: http://event-service
