spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: category_route
          uri: lb://category-service
          predicates:
            - Path=/categories/**
        - id: admin_category_route
          uri: lb://category-service
          predicates:
            - Path=/admin/categories/**

        - id: user_events_requests_route
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/events/{eventId}/requests/**

        - id: user_requests_route
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/requests/**

        - id: admin_requests_route
          uri: lb://request-service
          predicates:
            - Path=/admin/requests/**

        - id: admin_users_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        - id: events_route
          uri: lb://event-service
          predicates:
            - Path=/events/**
        - id: admin_events_route
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**

        - id: user_events_route
          uri: lb://event-service
          predicates:
            - Path=/users/{userId}/events/**

        - id: compilations_route
          uri: lb://event-service
          predicates:
            - Path=/compilations/**
        - id: admin_compilations_route
          uri: lb://event-service
          predicates:
            - Path=/admin/compilations/**

        - id: stats_route
          uri: lb://stats-server
          predicates:
            - Path=/stats/**
        - id: hit_route
          uri: lb://stats-server
          predicates:
            - Path=/hit/**

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    apache.kafka: WARN
    reactor.netty.http.server: DEBUG
