spring:
  application:
    name: main-server
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 10
        useRandomPolicy: true
        max-interval: 5000
      discovery:
        enabled: true
        serviceId: config-server

eureka:
  instance:
    preferIpAddress: false
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
